### PR TITLE
fix: changed express import to solve 'can only be default-imported us…

### PR DESCRIPTION
**Pull request by markus-mw**
## Description and context
Fix: 
```
src/index.ts(4,8): error TS1259: Module '"C:/Workspace/kroschke/connect-application/job/node_modules/@types/express/index"' can only be default-imported using the 'esModuleInterop' flag
```

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Brief description of the solution
Changed way of import.

## How was it tested?
Just run ``yarn dev`` after fix and you won't get the error anymore.

## Instructions to build/test locally
Just run ``yarn dev`` after fix and you won't get the error anymore.

## Depends on another PR/branch?

- [x] No
- [ ] Yes - dependant on PR/branch: 

## Checklist- 
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No error nor warning in the console.
- [ ] I joined a screenshot of the app before and after the fix.

[upload the screenshot here]

### CODE REVIEW

**Comment by ruidias-commercetools** [comment]
Hi @markus-mw, thank you for your contribution. 

Can you help me by giving me more details about this issue? 

What is your environment like when you run into this problem? What was the command that you ran? I just want to replicate the problem on my side.

Thanks,
Rui

**Comment by markus-mw** [comment]
Hi @ruidias-commercetools ,
I've installed node v16.20.0 on my system. I set up the connect application kit as described in https://github.com/commercetools/connect-application-kit. Then I tried to execute ``yarn start:dev`` in jobs directory to run it locally.
My IDE shows the issue, too.
image

**Comment by ruidias-commercetools** [comment]
Thank you for your answer. Can you also share your `package.json` and `tsconfig.json` files? Thanks

**Comment by markus-mw** [comment]
They are unchanged. As i can't upload JSON files, I've some links to the according state for you:

package.json 
-> https://github.com/commercetools/connect-application-kit/blob/%40commercetools-connect/create-connect-app%400.3.0/package.json

tsconfig.json 
-> https://github.com/commercetools/connect-application-kit/blob/%40commercetools-connect/create-connect-app%400.3.0/tsconfig.json

**Comment by ruidias-commercetools** [comment]
Thank you @markus-mw, we're looking into it.

**Pull request closed without merging**
